server:
  port: 8088
spring:
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.49.12:1521/orcl
    username: abc
    password: 123
# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml